name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: "none"

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_triple: ^2.0.1
  google_fonts: ^5.1.0
  ionicons: ^0.2.2
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0